version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;Database=todo;User Id=postgres;Password=haslo;
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo
      POSTGRES_DB: todo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge